# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storage.const


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(help_text='Width for use')),
                ('height', models.IntegerField(help_text='Height for use')),
                ('content', models.FileField(upload_to='')),
                ('size_bytes', models.BigIntegerField()),
                ('content_width', models.IntegerField(help_text='Content width')),
                ('content_height', models.IntegerField(help_text='Content height')),
                ('content_rotate_degree', models.IntegerField(default=0, help_text='How much content data must be rotated before use')),
                ('is_default', models.BooleanField()),
                ('mimetype', models.CharField(max_length=127)),
                ('workflow_type', models.IntegerField(choices=[(1, 'Raw'), (2, 'Original'), (3, 'Processed')])),
            ],
            options={
                'abstract': False,
            },
            bases=(storage.const.MediaConstMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.IntegerField(choices=[(1, 'Photo'), (2, 'Video')])),
                ('orientation', models.IntegerField(choices=[(1, 'Landscape'), (2, 'Portrait'), (3, 'Square')])),
                ('aspect_ratio', models.IntegerField(choices=[(1, '16:9'), (2, '4:3'), (3, '1:1'), (0, 'Other')])),
                ('shoot_at', models.DateTimeField()),
                ('device', models.CharField(blank=True, max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, height_field='thumbnail_height', upload_to='', width_field='thumbnail_width')),
                ('thumbnail_width', models.IntegerField(blank=True, null=True)),
                ('thumbnail_height', models.IntegerField(blank=True, null=True)),
                ('uploader', models.ForeignKey(help_text='User that uploaded the media. He owns it.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(storage.const.ShotConstMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShotCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(help_text='Width for use')),
                ('height', models.IntegerField(help_text='Height for use')),
                ('duration_seconds', models.DurationField()),
                ('content', models.FileField(upload_to='')),
                ('size_bytes', models.BigIntegerField()),
                ('content_width', models.IntegerField(help_text='Content width')),
                ('content_height', models.IntegerField(help_text='Content height')),
                ('content_rotate_degree', models.IntegerField(default=0, help_text='How much content data must be rotated before use')),
                ('is_default', models.BooleanField()),
                ('mimetype', models.CharField(max_length=127)),
                ('workflow_type', models.IntegerField(choices=[(1, 'Raw'), (2, 'Original'), (3, 'Processed')])),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Shot')),
            ],
            options={
                'abstract': False,
            },
            bases=(storage.const.MediaConstMixin, models.Model),
        ),
        migrations.AddField(
            model_name='photo',
            name='shot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Shot'),
        ),
    ]
