# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-27 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='gps_altitude_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
