# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20170127_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='gps_precision_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
