# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-29 15:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations
import lib.point_field


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_media_gps_precision_m'),
    ]

    operations = [
        HStoreExtension(),
        migrations.RemoveField(
            model_name='media',
            name='gps_latitude',
        ),
        migrations.RemoveField(
            model_name='media',
            name='gps_longitude',
        ),
        migrations.AddField(
            model_name='media',
            name='gps_location',
            field=lib.point_field.PointField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='location',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
    ]
