version: '2'

services:
  postgres:
    image: postgres:9.6 # 9.6.1
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    links:
      - postgres
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: utf-8
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONWARNINGS: all
      DATABASE_URL: postgres://user:password@postgres/app
      DJANGO_SETTINGS_MODULE: private_photo_cloud.settings.container
    volumes:
      - .:/home/app
    working_dir: /home/app
    command: python3 manage.py runserver 0.0.0.0:80
