version: '2'

services:
  db:
    image: postgres:9.6 # TODO: Use 9.6.1
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    links:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: utf-8
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONWARNINGS: all
    command: python3 -m http.server
