from django.utils.translation import pgettext, gettext

pgettext('month', 'January')
pgettext('month', 'February')
pgettext('month', 'March')
pgettext('month', 'April')
pgettext('month', 'May')
pgettext('month', 'June')
pgettext('month', 'July')
pgettext('month', 'August')
pgettext('month', 'September')
pgettext('month', 'October')
pgettext('month', 'November')
pgettext('month', 'December')

pgettext('of month', 'January')
pgettext('of month', 'February')
pgettext('of month', 'March')
pgettext('of month', 'April')
pgettext('of month', 'May')
pgettext('of month', 'June')
pgettext('of month', 'July')
pgettext('of month', 'August')
pgettext('of month', 'September')
pgettext('of month', 'October')
pgettext('of month', 'November')
pgettext('of month', 'December')

gettext('Monday')
gettext('Tuesday')
gettext('Wednesday')
gettext('Thursday')
gettext('Friday')
gettext('Saturday')
gettext('Sunday')
